import { createAsyncThunk, createSlice } from '@reduxjs/toolkit';
import { RootState } from '~/app/store';

export interface CounterState {
    MenuActive: boolean;
}

const initialState: CounterState = {
    MenuActive: false,
};

export const incrementAsync = createAsyncThunk('counter/fetchCount', async (amount: number) => {
    // const response = await fetchCount(amount);
    // The value we return becomes the `fulfilled` action payload
    // return response.data;
});

export const SidebarSlice = createSlice({
    name: 'sidebarActive',
    initialState,
    reducers: {
        toggleMenu: (state) => {
            state.MenuActive = !state.MenuActive;
        },
    },
    // The `extraReducers` field lets the slice handle actions defined elsewhere,
    // including actions generated by createAsyncThunk or in other slices.

    // extraReducers: (builder) => {
    //     builder
    //         .addCase(incrementAsync.pending, (state) => {
    //             state.status = 'loading';
    //         })
    //         .addCase(incrementAsync.fulfilled, (state, action) => {
    //             state.status = 'idle';
    //             state.value += action.payload;
    //         })
    //         .addCase(incrementAsync.rejected, (state) => {
    //             state.status = 'failed';
    //         });
    // },
});

export const { toggleMenu } = SidebarSlice.actions;

export const MenuActive = (state: RootState) => state.activeMenu.MenuActive;

export default SidebarSlice.reducer;
